## Numpy

Импортировать NumPy под именем np

In [112]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [7]:
v1 = np.zeros(10)
print(v1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Создать вектор размера 10, заполненный единицами

In [8]:
v2 = np.ones(10)
print(v2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Создать вектор размера 10, заполненный числом 2.5

In [9]:
v3 = np.ones(10)*2.5
print(v3)

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [10]:
v4 = np.zeros(10)
v4[4] = 1
print(v4)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Развернуть вектор (первый становится последним)

In [17]:
v5 = v4[::-1]
print(v5)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [27]:
v6 = np.arange(9)
v6 = v6.reshape(3,3)
print(v6)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [43]:
v7 = np.array([1,2,0,0,4,0])

print([i for i in range(len(v7)) if v7[i]>0])




[0, 1, 4]


Создать 3x3 единичную матрицу

In [45]:
v8 = np.ones(9)
v8 = v8.reshape(3,3)
print(v8)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Создать массив 3x3x3 со случайными значениями

In [50]:
v9 = np.random.random((3,3,3))
print(v9)

[[[0.61559657 0.76024069 0.00500986]
  [0.73242342 0.34202365 0.02538449]
  [0.08366702 0.07028193 0.86890192]]

 [[0.23539635 0.41644223 0.68091946]
  [0.88107873 0.74897883 0.70163132]
  [0.77874493 0.66509239 0.48630057]]

 [[0.11683495 0.96971866 0.38784699]
  [0.00802265 0.13941368 0.0694258 ]
  [0.38596015 0.69232624 0.56318602]]]


Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [52]:
v10 = np.random.random(30)
print(v10)
print(v10.mean())

[0.91444317 0.68469615 0.96622325 0.30459106 0.58369177 0.752732
 0.58721445 0.59361581 0.00726017 0.72297527 0.86943395 0.65661766
 0.40793068 0.69587754 0.60935316 0.13945681 0.672813   0.66227788
 0.40399286 0.8417627  0.27246769 0.80481654 0.97633455 0.97050043
 0.68646948 0.05134118 0.11523392 0.79777708 0.01195381 0.20765569]
0.5657169907153362


Перемножить матрицы 5x3 и 3x2

In [54]:
v11 = np.dot(np.random.random((5,3)), np.random.random((3,2)))
print(v11)

[[0.57520992 0.44524993]
 [0.51770615 0.31921579]
 [0.70689781 0.48810526]
 [0.55587599 0.43476448]
 [0.73907206 0.67184302]]


Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [184]:
v12 = np.arange(0.05,1,0.1)
print(v12)
print(v12.size)

[0.05 0.15 0.25 0.35 0.45 0.55 0.65 0.75 0.85 0.95]
10


Заменить максимальный элемент на ноль

In [185]:
print(v12.max())

#v12[[i for i in range(v12.size) if v12[i]==v12.max()]] = 0
v12[v12.argmax()]=0
print(v12)


0.9500000000000002
[0.05 0.15 0.25 0.35 0.45 0.55 0.65 0.75 0.85 0.  ]


Преобразовать массив из float в int

In [76]:
v13 = (v12*100).astype(np.int)
print(v13)

[ 5 15 25 35 45 55 65 75 85  0]


Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [181]:
v14 = np.random.random((10,2))
print(v14)

v15 = np.zeros((10,10))
for i in range(v15.shape[0]):
    for j in range(v15.shape[1]):
        v15[i,j] = np.sqrt(np.power(v14[i,0]- v14[j,0], 2) + np.power(v14[i,1]- v14[j,1], 2))
        
np.set_printoptions(precision = 4, suppress = True)
print(v15)


[[0.3209 0.9295]
 [0.2959 0.1696]
 [0.5307 0.0796]
 [0.7829 0.5489]
 [0.7912 0.2777]
 [0.9043 0.9853]
 [0.9782 0.6549]
 [0.103  0.5159]
 [0.7182 0.4893]
 [0.6788 0.606 ]]
[[0.     0.7603 0.8754 0.5986 0.8037 0.5861 0.7123 0.4675 0.593  0.4824]
 [0.7603 0.     0.2515 0.6173 0.507  1.0176 0.8373 0.3963 0.5297 0.5806]
 [0.8754 0.2515 0.     0.5328 0.3274 0.9798 0.7288 0.611  0.4506 0.5469]
 [0.5986 0.6173 0.5328 0.     0.2713 0.4529 0.2221 0.6807 0.088  0.1187]
 [0.8037 0.507  0.3274 0.2713 0.     0.7165 0.4209 0.7283 0.2238 0.347 ]
 [0.5861 1.0176 0.9798 0.4529 0.7165 0.     0.3385 0.9287 0.5298 0.4413]
 [0.7123 0.8373 0.7288 0.2221 0.4209 0.3385 0.     0.8861 0.3082 0.3033]
 [0.4675 0.3963 0.611  0.6807 0.7283 0.9287 0.8861 0.     0.6158 0.5828]
 [0.593  0.5297 0.4506 0.088  0.2238 0.5298 0.3082 0.6158 0.     0.1232]
 [0.4824 0.5806 0.5469 0.1187 0.347  0.4413 0.3033 0.5828 0.1232 0.    ]]


Случайно расположить p элементов в 2D массив

In [138]:
p = 10
v16 = np.random.random(p)
print(v16)
np.random.shuffle(v16)
print(v16)

[0.7876 0.8525 0.5278 0.4211 0.7852 0.4166 0.6719 0.3232 0.661  0.3914]
[0.8525 0.7852 0.6719 0.661  0.3232 0.5278 0.3914 0.7876 0.4166 0.4211]


Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [207]:
v17 = np.array([1,2,3,4,5])
print(v17)
v177 = np.zeros(len(v17) + (len(v17)-1)*(3))
v177[::4] = v17
v177 = v177.astype(np.int)
print(v177)

[1 2 3 4 5]
[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


Найти наиболее частое значение в массиве

In [208]:
print(np.bincount(v177).argmax())

0


Найти n наибольших значений в массиве

In [202]:
v18 = np.random.randint(0, 100, (25))
n = 5
print(v18)
max_items = []
for i in range(1,n+1):
    max_items.append(v18[v18.argmax()])
    v18 = np.delete(v18, v18.argmax())
    
print(max_items)

[62 96 70 70 99 46 94 87 69 97 59 43 79 46 63 85 45 38 16 73 78 30 39 33
 54]
[99, 97, 96, 94, 87]


## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [7]:
import pandas as pd
food_sample = pd.read_table('d:\\Downloads\\world-food-facts\\en.openfoodfacts.org.products.tsv', nrows=1000)
col_names = food_sample.dtypes.index.values
dtypes_values = food_sample.dtypes.values
print(sum(food_sample.memory_usage().values)/(1024*1024))
dtypes = {col_names[i]: dtypes_values[i] for i in range(len(col_names))}

#food = pd.read_table('d:\\Downloads\\world-food-facts\\en.openfoodfacts.org.products.tsv', 
#                          sep='\t', dtype=dtypes, error_bad_lines=False, warn_bad_lines=True, low_memory=False)

food = pd.read_table('d:\\Downloads\\world-food-facts\\en.openfoodfacts.org.products.tsv', 
                          sep='\t', error_bad_lines=False, warn_bad_lines=True, low_memory=False)




1.2436676025390625
442.75215911865234


Посмотреть первые 5 записей

In [13]:

print(sum(food.memory_usage().values)/(1024*1024))
food.head(5)

442.75215911865234


code                                                url  \
0  0000000003087  http://world-en.openfoodfacts.org/product/0000...   
1  0000000004530  http://world-en.openfoodfacts.org/product/0000...   
2  0000000004559  http://world-en.openfoodfacts.org/product/0000...   
3  0000000016087  http://world-en.openfoodfacts.org/product/0000...   
4  0000000016094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)   
2      1489069957   2017-03-09T14:32:37Z                         Peanuts   
3      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix   
4      1489055653   2017-03-09T10:34:13Z                 Organic Polenta   

  generic_name quantity         ...         fruits-vegetables-nuts_100g  \
0          NaN      1kg         ...                                 NaN   
1          NaN      NaN         ...                                 NaN   
2          NaN      NaN         ...                                 NaN   
3          NaN      NaN         ...                                 NaN   
4          NaN      NaN         ...                                 NaN   

  fruits-vegetables-nuts-estimate_100g collagen-meat-protein-ratio_100g  \
0                                  NaN                              NaN   
1                                  NaN                              NaN   
2                                  NaN                              NaN   
3                                  NaN                              NaN   
4                                  NaN                              NaN   

  cocoa_100g chlorophyl_100g carbon-footprint_100g nutrition-score-fr_100g  \
0        NaN             NaN                   NaN                     NaN   
1        NaN             NaN                   NaN                    14.0   
2        NaN             NaN                   NaN                     0.0   
3        NaN             NaN                   NaN                    12.0   
4        NaN             NaN                   NaN                     NaN   

  nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
0                     NaN                 NaN                 NaN  
1                    14.0                 NaN                 NaN  
2                     0.0                 NaN                 NaN  
3                    12.0                 NaN                 NaN  
4                     NaN                 NaN                 NaN  

[5 rows x 163 columns]

Сколько наблюдений в наборе данных?


In [9]:
food.size

58032401

Сколько столбцов в наборе данных?

In [18]:
food.columns.size

163

Напечатайте все названия столбцов

In [21]:
print(food.columns.values)

['code' 'url' 'creator' 'created_t' 'created_datetime' 'last_modified_t'
 'last_modified_datetime' 'product_name' 'generic_name' 'quantity'
 'packaging' 'packaging_tags' 'brands' 'brands_tags' 'categories'
 'categories_tags' 'categories_en' 'origins' 'origins_tags'
 'manufacturing_places' 'manufacturing_places_tags' 'labels' 'labels_tags'
 'labels_en' 'emb_codes' 'emb_codes_tags' 'first_packaging_code_geo'
 'cities' 'cities_tags' 'purchase_places' 'stores' 'countries'
 'countries_tags' 'countries_en' 'ingredients_text' 'allergens'
 'allergens_en' 'traces' 'traces_tags' 'traces_en' 'serving_size'
 'no_nutriments' 'additives_n' 'additives' 'additives_tags' 'additives_en'
 'ingredients_from_palm_oil_n' 'ingredients_from_palm_oil'
 'ingredients_from_palm_oil_tags'
 'ingredients_that_may_be_from_palm_oil_n'
 'ingredients_that_may_be_from_palm_oil'
 'ingredients_that_may_be_from_palm_oil_tags' 'nutrition_grade_uk'
 'nutrition_grade_fr' 'pnns_groups_1' 'pnns_groups_2' 'states'
 'states_tags' 

Какое название у 105 столбца?

In [28]:
print(food.columns.values[104])

-glucose_100g


Какой тип наблюдений в 105 столбце?

In [27]:
print(food.dtypes[104])

float64


Как проиндексирован набор данных?

In [29]:
food.index

RangeIndex(start=0, stop=356027, step=1)

Каково значение имени продукта в 19-м наблюдении?

In [35]:
food.loc[18, 'product_name']

'Lotus Organic Brown Jasmine Rice'

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [133]:
chipo = pd.read_table('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv',
                     error_bad_lines=False, warn_bad_lines=True, low_memory=False)

Как много продуктов стоят более чем $10.00?

In [134]:

price = np.array([float(x.replace('$','')) for x in chipo.item_price.values])
chipo.item_price = price
price[price>10].size

1130

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [135]:
print(chipo.loc[:,('item_name','item_price')])

                                  item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
5                              Chicken Bowl       10.98
6                             Side of Chips        1.69
7                             Steak Burrito       11.75
8                          Steak Soft Tacos        9.25
9                             Steak Burrito        9.25
10                      Chips and Guacamole        4.45
11                     Chicken Crispy Tacos        8.75
12                       Chicken Soft Tacos        8.75
13                             Chicken Bowl       11.25
14                      Chips and Guacamole        4.45
15    Chips and Tomatillo-Green Chili Salsa        2.39
16                          Chicken Burrito     

Отсортировать по имени предмета

In [136]:
chipo.sort_values(by=['item_name'])

order_id  quantity          item_name  \
3389      1360         2  6 Pack Soft Drink   
341        148         1  6 Pack Soft Drink   
1849       749         1  6 Pack Soft Drink   
1860       754         1  6 Pack Soft Drink   
2713      1076         1  6 Pack Soft Drink   
3422      1373         1  6 Pack Soft Drink   
553        230         1  6 Pack Soft Drink   
1916       774         1  6 Pack Soft Drink   
1922       776         1  6 Pack Soft Drink   
1937       784         1  6 Pack Soft Drink   
3836      1537         1  6 Pack Soft Drink   
298        129         1  6 Pack Soft Drink   
1976       798         1  6 Pack Soft Drink   
1167       481         1  6 Pack Soft Drink   
3875      1554         1  6 Pack Soft Drink   
1124       465         1  6 Pack Soft Drink   
3886      1558         1  6 Pack Soft Drink   
2108       849         1  6 Pack Soft Drink   
3010      1196         1  6 Pack Soft Drink   
4535      1803         1  6 Pack Soft Drink   
4169      1664         1  6 Pack Soft Drink   
4174      1666         1  6 Pack Soft Drink   
4527      1800         1  6 Pack Soft Drink   
4522      1798         1  6 Pack Soft Drink   
3806      1525         1  6 Pack Soft Drink   
2389       949         1  6 Pack Soft Drink   
3132      1248         1  6 Pack Soft Drink   
3141      1253         1  6 Pack Soft Drink   
639        264         1  6 Pack Soft Drink   
1026       422         1  6 Pack Soft Drink   
...        ...       ...                ...   
2996      1192         1       Veggie Salad   
3163      1263         1       Veggie Salad   
4084      1635         1       Veggie Salad   
1694       686         1       Veggie Salad   
2756      1094         1       Veggie Salad   
4201      1677         1  Veggie Salad Bowl   
1884       760         1  Veggie Salad Bowl   
455        195         1  Veggie Salad Bowl   
3223      1289         1  Veggie Salad Bowl   
2223       896         1  Veggie Salad Bowl   
2269       913         1  Veggie Salad Bowl   
4541      1805         1  Veggie Salad Bowl   
3293      1321         1  Veggie Salad Bowl   
186         83         1  Veggie Salad Bowl   
960        394         1  Veggie Salad Bowl   
1316       536         1  Veggie Salad Bowl   
2156       869         1  Veggie Salad Bowl   
4261      1700         1  Veggie Salad Bowl   
295        128         1  Veggie Salad Bowl   
4573      1818         1  Veggie Salad Bowl   
2683      1066         1  Veggie Salad Bowl   
496        207         1  Veggie Salad Bowl   
4109      1646         1  Veggie Salad Bowl   
738        304         1  Veggie Soft Tacos   
3889      1559         2  Veggie Soft Tacos   
2384       948         1  Veggie Soft Tacos   
781        322         1  Veggie Soft Tacos   
2851      1132         1  Veggie Soft Tacos   
1699       688         1  Veggie Soft Tacos   
1395       567         1  Veggie Soft Tacos   

                                     choice_description  item_price  
3389                                        [Diet Coke]       12.98  
341                                         [Diet Coke]        6.49  
1849                                             [Coke]        6.49  
1860                                        [Diet Coke]        6.49  
2713                                             [Coke]        6.49  
3422                                             [Coke]        6.49  
553                                         [Diet Coke]        6.49  
1916                                        [Diet Coke]        6.49  
1922                                             [Coke]        6.49  
1937                                        [Diet Coke]        6.49  
3836                                             [Coke]        6.49  
298                                            [Sprite]        6.49  
1976                                        [Diet Coke]        6.49  
1167                                             [Coke]        6.49  
3875                                     

Сколько было заказано самого дорогого предмета?

In [145]:
#print(chipo.item_price.max())

chipo.loc[chipo.loc[:,'item_price'] == chipo.item_price.max(), 'quantity']

3598    15
Name: quantity, dtype: int64

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [163]:
grouped = chipo.groupby('item_name')
grouped.sum().loc['Veggie Salad Bowl','quantity']


18

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [173]:
soda  = chipo[chipo.item_name == "Canned Soda"]
soda[soda.quantity>1].count()

order_id              20
quantity              20
item_name             20
choice_description    20
item_price            20
dtype: int64